version: '3.1'

services:
  server:
    build:
        context: ".."
        dockerfile: rpi/Dockerfile
    container_name: "rld-node"
    environment:
      RLD_MAPTOOL_HOSTNAME: ${RLD_MAPTOOL_HOSTNAME}
      RLD_MAPTOOL_PORT: ${RLD_MAPTOOL_PORT}
